//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASMTravel.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Comment
    {
        
        public int CommentID { get; set; }
        [StringLength(10, ErrorMessage = "{0} is too long")]
        [Required(ErrorMessage = "{0} is required")]
        [DisplayName("Post ID")]
        public string PostID { get; set; }
        [StringLength(255, ErrorMessage = "{0} is too long")]
        [Required(ErrorMessage = "{0} is required")]
        [DisplayName("Comment Name or Email")]
        public string CmEmail { get; set; }
        [StringLength(1000, ErrorMessage = "{0} is too long")]
        [Required(ErrorMessage = "{0} is required")]
        [DisplayName("Message")]
        public string CmDescription { get; set; }
        [DisplayName("Status")]
        public Nullable<int> CmStatus { get; set; }
    
        public virtual Post Post { get; set; }
    }
}
