//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASMTravel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public string ContractID { get; set; }
        public string CustomerID { get; set; }
        public System.DateTime ContractDateTime { get; set; }
        public string ContractDescription { get; set; }
        public Nullable<int> ContractStatus { get; set; }
    }
}
