//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASMTravel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public string CustomerID { get; set; }
        public string CustomerName { get; set; }
        public string Nationality { get; set; }
        public string Passport { get; set; }
        public string CsAddress { get; set; }
        public string CsPhone { get; set; }
        public string CsEmail { get; set; }
        public Nullable<int> CsStatus { get; set; }
    }
}
