//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASMTravel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel
    {
        public string HotelID { get; set; }
        public Nullable<int> RoomType { get; set; }
        public string HotelName { get; set; }
        public string HotelAddress { get; set; }
        public string HotelPhone { get; set; }
        public Nullable<double> HotelAmount { get; set; }
        public Nullable<int> HotelStatus { get; set; }
    }
}
