//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASMTravel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlacePost
    {
        public string PlacePostID { get; set; }
        public string PlaceID { get; set; }
        public string PostID { get; set; }
    }
}
