//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASMTravel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurant
    {
        public string RestaurantID { get; set; }
        public string ReName { get; set; }
        public string ReAddress { get; set; }
        public string RePhone { get; set; }
        public Nullable<double> RePrice { get; set; }
        public Nullable<int> ReStatus { get; set; }
    }
}
