//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASMTravel.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Staff
    {
        [StringLength(10, ErrorMessage = "{0} is too long")]
        [Required(ErrorMessage = "{0} is required")]
        [DisplayName("Staff ID")]
        public string StaffID { get; set; }
        [StringLength(255, ErrorMessage = "{0} is too long")]
        [Required(ErrorMessage = "{0} is required")]
        [DisplayName("Full Name")]
        public string Fullname { get; set; }
        [StringLength(10, ErrorMessage = "{0} is too long")]
        [Required(ErrorMessage = "{0} is required")]
        [DisplayName("Gender")]
        public string Sex { get; set; }
        [StringLength(255, ErrorMessage = "{0} is too long")]
        [Required(ErrorMessage = "{0} is required")]
        [DisplayName("Address")]
        public string Address { get; set; }
        [StringLength(255, ErrorMessage = "{0} is too long")]
        [Required(ErrorMessage = "{0} is required")]
        [DisplayName("Email")]
        public string Email { get; set; }
        [StringLength(15, ErrorMessage = "{0} is too long")]
        [Required(ErrorMessage = "{0} is required")]
        [DisplayName("Phone Number")]
        public string Phone { get; set; }
        [StringLength(255, ErrorMessage = "{0} is too long")]
        [Required(ErrorMessage = "{0} is required")]
        [DisplayName("Password")]
        public string password { get; set; }
        [StringLength(255, ErrorMessage = "{0} is too long")]
        [Required(ErrorMessage = "{0} is required")]
        [DisplayName("Username")]
        public string username { get; set; }
        public Nullable<int> Role { get; set; }
        public Nullable<int> StStatus { get; set; }
    }
}
