//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASMTravel.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class TourDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TourDetail()
        {
            this.Tours = new HashSet<Tour>();
        }
        [StringLength(10, ErrorMessage = "{0} is too long")]
        [DisplayName("Tour Detail ID")]
        public string TourDetailsID { get; set; }

        [StringLength(10, ErrorMessage = "{0} is too long")]
        [Required(ErrorMessage = "{0} is required")]
        [DisplayName("Place ID")]
        public string PlaceID { get; set; }

        [DisplayName("Service ID")]
        public string ServiceID { get; set; }

        [DataType(DataType.MultilineText)]
        [StringLength(1000, ErrorMessage = "{0} is too long")]
        [Required(ErrorMessage = "{0} is required")]
        [DisplayName("Tour Description")]
        public string TdDescription { get; set; }

        [DisplayName("Status")]
        public Nullable<int> TdStatus { get; set; }

    
        public virtual Place Place { get; set; }

        public virtual Service Service { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tour> Tours { get; set; }
    }
}
