//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASMTravel.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Tour
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tour()
        {
            this.TourRegisters = new HashSet<TourRegister>();
        }
        [StringLength(10, ErrorMessage = "{0} is too long")]
        [Required(ErrorMessage = "{0} is required")]
        [DisplayName("Tour ID")]
        public string TourID { get; set; }

        [StringLength(10, ErrorMessage = "{0} is too long")]
        [Required(ErrorMessage = "{0} is required")]
        [DisplayName("Tour Detail ID")]
        public string TourDetailsID { get; set; }

        [StringLength(255, ErrorMessage = "{0} is too long")]
        [Required(ErrorMessage = "{0} is required")]
        [DisplayName("Tour Name")]
        public string TourName { get; set; }

        [StringLength(50, ErrorMessage = "{0} is too long")]
        [Required(ErrorMessage = "{0} is required")]
        [DisplayName("Time of Tour")]
        public string Time { get; set; }

      
        [Required(ErrorMessage = "{0} is required")]
        [DisplayName("Tour Amount")]
        public Nullable<double> TourAmount { get; set; }

        
        [DisplayName("Status")]
        public Nullable<int> TourStatus { get; set; }

       
        [DisplayName("Image ID")]
        public Nullable<int> ImgID { get; set; }

    
        public HttpPostedFileBase LoadImage { get; set; }

        public virtual Image Image { get; set; }

        public virtual TourDetail TourDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TourRegister> TourRegisters { get; set; }
    }
}
