//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASMTravel.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class TourRegister
    {

        [Required(ErrorMessage = "{0} is required")]
        [DisplayName("Tour Register ID")]
        public int TourRegisterID { get; set; }

        [StringLength(10, ErrorMessage = "{0} is too long")]
        [Required(ErrorMessage = "{0} is required")]
        [DisplayName("Tour ID")]
        public string TourID { get; set; }

        [StringLength(255, ErrorMessage = "{0} is too long")]
        [Required(ErrorMessage = "{0} is required")]
        [DisplayName("Name Customer")]
        public string Name { get; set; }


        [Required(ErrorMessage = "{0} is required")]
        [DisplayName("Date Register")]
        public System.DateTime DateCreate { get; set; }

        [StringLength(255, ErrorMessage = "{0} is too long")]
        [Required(ErrorMessage = "{0} is required")]
        [DisplayName("Address")]
        public string Address { get; set; }

        [StringLength(15, ErrorMessage = "{0} is too long")]
        [Required(ErrorMessage = "{0} is required")]
        [DisplayName("Phone Number")]
        public string Phone { get; set; }

        [StringLength(255, ErrorMessage = "{0} is too long")]
        [Required(ErrorMessage = "{0} is required")]
        [DisplayName("Email")]
        public string Email { get; set; }


        [Required(ErrorMessage = "{0} is required")]
        [DisplayName("Ticket")]
        public Nullable<int> NumberOfTicket { get; set; }


        
        [DisplayName("Message")]
        public string Message { get; set; }

       
        [DisplayName("Status")]
        public Nullable<int> status { get; set; }
    
        public virtual Tour Tour { get; set; }
    }
}
